### ISSUE TITLE
Upgrade the C4-PlantUML code to 2.8.0

### ISSUE THREAD

**Issue by YBAZAN** [8T4/c4sharp#43]
As I see in the code, the version of the C4-PlantUML code is "2.6.0beta1" whereas the official release is now up to the "2.8.0" version.
These are the release notes:

![image](https://github.com/8T4/c4sharp/assets/40167348/fe65ff99-172d-4a84-9524-8e4b543f11ac)

![image](https://github.com/8T4/c4sharp/assets/40167348/5e501cdd-0ac6-4e44-8411-8d9a187bac45)

Would it be possible to update the code here to use the latest additions ?

**Comment by yanjustino** [comment]
**Hello**,

We sincerely appreciate you taking the time to open an issue. Your contribution is very important to us and helps us to continuously improve our project. Please be informed that your issue is currently under review and will be addressed as soon as possible by our team. Stay tuned for updates, and feel free to add any additional information if necessary.

Best regards,
Yan Justino

**Comment by yanjustino** [comment]
### 📦 Release

We released a new version 6.2.x  🚀 of C4Sharp. The release includes new improvements such as minor bug fixes to the write test log, code maintainability, and performance. You can read the full list of new enhancements and bug fixes below:

####  Commits on Dec 25, 2022
- Fixing NameSpaces (Please update your project to use the correct namespaces)
- Update plantuml.jar
- Update C4-plantuml files in Resource
- Add new SequenceDiagram [See the sample](https://github.com/8T4/c4sharp/blob/main/samples/Basic/C4Sharp.Sample/Diagrams/SequenceDiagram.cs)

![image](https://github.com/8T4/c4sharp/assets/357114/bf155e5c-c61a-46e8-ab6a-69b4b23bdadd)



- Update ElementStyle.cs to accept UpdateElementStyle(...,?borderStyle, ?borderThickness)
- Removing support to .NET 5.0
