### ISSUE TITLE
C4SCLI not compatible with .NET 5.0 or .NET 6.0

### ISSUE THREAD

**Issue by dylangendreau** [8T4/c4sharp#44]
When trying to install the C4SCLI nuget package on any net5.0 or net6.0 project, error NU1202 happens.

> NU1202	Package c4scli 2.1.166 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package c4scli 2.1.166 supports:
>   - net5.0 (.NETCoreApp,Version=v5.0) / any
>   - net6.0 (.NETCoreApp,Version=v6.0) / any

This clearly states that it supports any version of net5.0 or net6.0, but every project I've tried to install it on so far, this error appears.

**Comment by yanjustino** [comment]
**Hello**,

We sincerely appreciate you taking the time to open an issue. Your contribution is very important to us and helps us to continuously improve our project. Please be informed that your issue is currently under review and will be addressed as soon as possible by our team. Stay tuned for updates, and feel free to add any additional information if necessary.

Best regards,
Yan Justino

**Comment by yanjustino** [comment]
### 📦 Release

We released a new version 6.2.x  🚀 of C4Sharp. The release includes new improvements such as minor bug fixes to the write test log, code maintainability, and performance. You can read the full list of new enhancements and bug fixes below:

####  Commits on Dec 25, 2022
- Fixing NameSpaces (Please update your project to use the correct namespaces)
- Update plantuml.jar
- Update C4-plantuml files in Resource
- Add new SequenceDiagram [See the sample](https://github.com/8T4/c4sharp/blob/main/samples/Basic/C4Sharp.Sample/Diagrams/SequenceDiagram.cs)

![image](https://github.com/8T4/c4sharp/assets/357114/bf155e5c-c61a-46e8-ab6a-69b4b23bdadd)



- Update ElementStyle.cs to accept UpdateElementStyle(...,?borderStyle, ?borderThickness)
- Removing support to .NET 5.0
